<a href="https://colab.research.google.com/github/junda29/H8_Telkom/blob/master/Latihan_Sesi_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
class Conv3x3:
  """Convolutional layers using 3x3 filters"""
  def __init__(self,out_channel: int):
    self.out_channel = out_channel
    self.filter = np.random.randint(-1,1, (out_channel,3,3))

  def _region(self, image):
    """Generate all posibles 3x3 receptive field form 2D image."""
    h, w =image.shape
    for hi in range(h-2):
      for wi in range(w-2):
        region = image [hi:(hi+3), wi: (wi+3)]
        yield region, hi, wi
  def convolve(self, image):
    """Do convolution over image"""
    h, w = image.shape
    out_dim = (h-2, w-2, self.out_channel)
    output = np.zeros(out_dim)

    for region, hi, wi, in self._region(image):
      output [hi,wi] = np.sum(region*self.filter, axis=(1,2))
    return output


In [3]:
np.random.seed(11)

In [6]:
# generate random image
image=np.random.randint(0,10, size=(5,5))
print("Random Image:")
print(image)

Random Image:
[[9 0 1 7 1]
 [7 2 8 0 0]
 [4 2 1 5 5]
 [7 4 1 8 8]
 [1 3 6 2 2]]


In [7]:
#instatituate Conv3x3 onject
conv = Conv3x3(out_channel=5)
print("filter size:", conv.filter.shape)
print("filter;")
print(conv.filter)

output = conv.convolve(image)
print("Output shape:", output.shape)
print("Output:")
print(output)

filter size: (5, 3, 3)
filter;
[[[-1  0  0]
  [-1  0  0]
  [-1  0  0]]

 [[-1  0  0]
  [-1  0 -1]
  [ 0  0  0]]

 [[-1 -1 -1]
  [ 0 -1  0]
  [ 0  0  0]]

 [[-1  0  0]
  [ 0 -1  0]
  [-1  0  0]]

 [[-1 -1 -1]
  [-1 -1  0]
  [ 0  0 -1]]]
Output shape: (3, 3, 5)
Output:
[[[-20. -24. -12. -15. -20.]
  [ -4.  -2. -16. -10. -23.]
  [-10.  -9.  -9.  -2. -22.]]

 [[-18. -12. -19. -16. -24.]
  [ -8.  -9. -11.  -7. -21.]
  [-10. -14. -13. -14. -22.]]

 [[-12. -12. -11.  -9. -24.]
  [ -9. -14.  -9.  -6. -15.]
  [ -8. -10. -19. -15. -22.]]]
