In [2]:
import numpy as np

In [5]:
firstArray = np.array([1,2,3,4])

In [6]:
firstArray

array([1, 2, 3, 4])

In [7]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.empty(3)

array([5.50901604e-279, 1.26585842e-306, 3.38460713e+125])

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(2,9)

array([2, 3, 4, 5, 6, 7, 8])

In [13]:
np.arange(-5,0)

array([-5, -4, -3, -2, -1])

In [14]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(1,7,4)

array([1, 5])

In [16]:
arr=np.array([1,2,3,4,5,6])

In [17]:
arr

array([1, 2, 3, 4, 5, 6])

In [18]:
np.append(arr,[100,200])

array([  1,   2,   3,   4,   5,   6, 100, 200])

In [19]:
np.delete(arr,1)

array([1, 3, 4, 5, 6])

In [21]:
array_example = np.array([[[0,1,2,3],
                           [[0,1,2,3]],
                           [0,1,2,3]]])

In [24]:
array_example

array([[list([0, 1, 2, 3]), list([[0, 1, 2, 3]]), list([0, 1, 2, 3])]],
      dtype=object)

In [25]:
coba=[[1,2,3],[1,2,3]]

In [26]:
coba

[[1, 2, 3], [1, 2, 3]]

In [28]:
coba2=coba*100

In [29]:
coba2

[[1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1,

In [34]:
a=np.array([0,1,2,3,4,5])

In [35]:
a

array([0, 1, 2, 3, 4, 5])

In [36]:
a.shape

(6,)

In [37]:
a2=a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[0 1 2 3 4 5]]


In [38]:
a

array([0, 1, 2, 3, 4, 5])

In [41]:
print(a)
print(a[0])
print(a[2])

[0 1 2 3 4 5]
0
2


In [44]:
a[0:4]

array([0, 1, 2, 3])

In [45]:
newArray = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]])

In [46]:
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
newArray[newArray>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [50]:
newArray[(newArray>=1)&(newArray<=5)]

array([1, 2, 3, 4, 5])

In [52]:
arr=np.arange(1,11)

In [53]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr1=arr[3:8]

In [55]:
arr1

array([4, 5, 6, 7, 8])

In [56]:
a_1=np.array([[1,1],
             [2,2]])

In [57]:
a_2=np.array([[3,3],
             [4,4]])

In [59]:
print(a_1)
print(a_2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [61]:
np.vstack((a_1,a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [62]:
np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [63]:
data = np.array([1,2])

In [64]:
ones = np.ones(2)

In [65]:
data + ones

array([2., 3.])

In [66]:
data - ones

array([0., 1.])

In [67]:
data

array([1, 2])

In [68]:
ones

array([1., 1.])

In [69]:
data.sum()

3

In [70]:
a

array([0, 1, 2, 3, 4, 5])

In [71]:
a.sum()

15

In [73]:
b=np.array([[1,2],[2,2]])

In [74]:
b

array([[1, 2],
       [2, 2]])

In [76]:
b.sum()

7

In [77]:
b.sum(axis=1)

array([3, 4])

In [79]:
b.sum(axis=0)

array([3, 4])

In [80]:
data

array([1, 2])

In [81]:
data*2

array([2, 4])

In [82]:
2*data

array([2, 4])

In [83]:
data

array([1, 2])

In [84]:
data = np.array([[1,2,3,4,5,6],
                [7,8,9,10,11,12],
                [13,14,15,16,17,18]])

In [85]:
data

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [86]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [88]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [89]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [94]:
np.random.random((2,3))

array([[0.66381488, 0.82616311, 0.80473906],
       [0.29880618, 0.72624395, 0.75228876]])

In [96]:
data = np.array([[1,2],[3,4]])

In [103]:
ones = np.ones((2,2))

In [104]:
ones

array([[1., 1.],
       [1., 1.]])

In [105]:
data

array([[1, 2],
       [3, 4]])

In [106]:
data + ones

array([[2., 3.],
       [4., 5.]])

In [107]:
data*ones

array([[1., 2.],
       [3., 4.]])

In [108]:
ones2=np.ones((1,2))

In [109]:
ones2

array([[1., 1.]])

In [110]:
data*ones2

array([[1., 2.],
       [3., 4.]])

In [112]:
a_1=np.array([[1,2,3],[4,5,6]])

In [113]:
a_1

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
a_2=np.array([[1,2],[3,4],[5,6]])

In [115]:
a_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [118]:
np.dot(a_1,a_2)

array([[22, 28],
       [49, 64]])

In [119]:
10*a_1

array([[10, 20, 30],
       [40, 50, 60]])

In [120]:
data1 = np.array([[1,2],[3,4],[5,6]])

In [121]:
data1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [123]:
data1[0]

array([1, 2])

In [124]:
data1[0,1]

2

In [125]:
data1[:,0]

array([1, 3, 5])

In [127]:
data2=data1[:,0]

In [128]:
print(data2.T)

[1 3 5]


In [129]:
a_1

array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
a_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [132]:
a_3=np.dot(a_1.T,a_2.T)

In [133]:
a_3

array([[ 9, 19, 29],
       [12, 26, 40],
       [15, 33, 51]])

In [134]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [135]:
np.ones((3,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])